services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Valantic\DataQualityBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']


    Valantic\DataQualityBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']


    Valantic\DataQualityBundle\Installer\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('ValanticDataQualityBundle')"


    Valantic\DataQualityBundle\Service\:
        resource: '../../Service'

    Valantic\DataQualityBundle\Repository\:
        resource: '../../Repository'

    Valantic\DataQualityBundle\Repository\ConstraintDefinitions:
        arguments:
            - !tagged_iterator validator.constraint_validator


    Valantic\DataQualityBundle\Config\V1\Constraints\Reader: ~

    Valantic\DataQualityBundle\Config\V1\Constraints\Writer: ~

    Valantic\DataQualityBundle\Config\V1\Meta\Reader: ~

    Valantic\DataQualityBundle\Config\V1\Meta\Writer: ~

    Valantic\DataQualityBundle\Validation\ValidateDataObject: ~
